baseURL = "https://rafamacedo.dev"
author = "Rafael Macedo"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 6
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# ------------------------------

theme = "paper"
title = "Rafael Macedo"

[params]
  twitter = 'manodoscodigos'
  github = 'rafaelmacedox'
  instagram = 'orafa.macedo'

# ------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre/"
    weight = 1

  [[menu.main]]
    identifier = "projetos"
    name = "Projetos"
    url = "/projetos/"
    weight = 2

  [[menu.main]]
    identifier = "biblioteca"
    name = "Biblioteca"
    url = "/biblioteca/"
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
